// Action Types for Redux Store
export const actionTypes = {
  // Auth actions
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",

  // Sheets actions
  FETCH_SHEETS_REQUEST: "FETCH_SHEETS_REQUEST",
  FETCH_SHEETS_SUCCESS: "FETCH_SHEETS_SUCCESS",
  FETCH_SHEETS_FAILURE: "FETCH_SHEETS_FAILURE",
  UPDATE_SHEET_DATA: "UPDATE_SHEET_DATA",

  // Drive actions
  FETCH_FILES_REQUEST: "FETCH_FILES_REQUEST",
  FETCH_FILES_SUCCESS: "FETCH_FILES_SUCCESS",
  FETCH_FILES_FAILURE: "FETCH_FILES_FAILURE",
  UPLOAD_FILE_REQUEST: "UPLOAD_FILE_REQUEST",
  UPLOAD_FILE_SUCCESS: "UPLOAD_FILE_SUCCESS",
  UPLOAD_FILE_FAILURE: "UPLOAD_FILE_FAILURE",

  // Dashboard actions
  FETCH_DASHBOARD_DATA: "FETCH_DASHBOARD_DATA",
  UPDATE_DASHBOARD_DATA: "UPDATE_DASHBOARD_DATA",
  SET_ACTIVE_TAB: "SET_ACTIVE_TAB",

  // Alerts actions
  SHOW_ALERT: "SHOW_ALERT",
  HIDE_ALERT: "HIDE_ALERT",
  CLEAR_ALL_ALERTS: "CLEAR_ALL_ALERTS",
};
